"""Core app services (settings, logging, lifecycle)."""

from app.core.constants import (
    AUTH_BEARER_SCHEME,
    AUTH_PASSWORD_HASH_DIGEST,
    AUTH_PASSWORD_HASH_ITERATIONS,
    AUTH_PASSWORD_HASH_SALT_BYTES,
    AUTH_PASSWORD_HASH_SCHEME,
    AUTH_REQUIRED_TOKEN_CLAIMS,
    AUTH_TOKEN_TYPE_ACCESS,
    GRADING_DEFAULT_MODEL,
    GRADING_DEFAULT_PROMPT_VERSION,
    GRADING_PROVIDER_MOCK,
    GRADING_PROVIDER_OPENAI_COMPATIBLE,
    GRADING_SUPPORTED_PROVIDERS,
    HIGHLIGHT_CODES,
    HIGHLIGHT_CODE_TO_LABEL,
    INTENT_CODES,
    INTENT_CODE_TO_LABEL,
)
from app.core.config import Settings, get_settings

__all__ = [
    "AUTH_BEARER_SCHEME",
    "AUTH_PASSWORD_HASH_DIGEST",
    "AUTH_PASSWORD_HASH_ITERATIONS",
    "AUTH_PASSWORD_HASH_SALT_BYTES",
    "AUTH_PASSWORD_HASH_SCHEME",
    "AUTH_REQUIRED_TOKEN_CLAIMS",
    "AUTH_TOKEN_TYPE_ACCESS",
    "GRADING_DEFAULT_MODEL",
    "GRADING_DEFAULT_PROMPT_VERSION",
    "GRADING_PROVIDER_MOCK",
    "GRADING_PROVIDER_OPENAI_COMPATIBLE",
    "GRADING_SUPPORTED_PROVIDERS",
    "HIGHLIGHT_CODES",
    "HIGHLIGHT_CODE_TO_LABEL",
    "INTENT_CODES",
    "INTENT_CODE_TO_LABEL",
    "Settings",
    "get_settings",
]
